# Generated by Django 4.2.3 on 2023-07-28 01:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("freight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="freight",
            name="external_freight_id",
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, unique=True),
        ),
    ]
