# Generated by Django 4.2.3 on 2023-07-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.UUIDField(unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wheigth', models.DecimalField(decimal_places=2, max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('zip_from', models.CharField(max_length=8)),
                ('zip_to', models.CharField(max_length=8)),
            ],
        ),
    ]
